#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

check_run() {
	echo "$changed_files" | grep --quiet "$1" && eval "$2"
}

# Example usage
# In this example it's used to run `pnpm install` if package.json changed.
check_run package.json "pnpm install"

