#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"


protected_branches=('origin/develop' 'main' 'develop')
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
 
for branch in "${protected_branches[@]}"
do
    if [ $branch = $current_branch ]; then
        echo "You're about to push $branch and you don't want to do that!"
				echo "Please ensure you are pushing to an issue-based branch"
				echo "in the format of: YourName/##-short-description"
				echo "where ## is the Issue number."
        exit 1
    fi
done
exit 0
