#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
. "$(dirname "$0")/common.sh"

TMP_FILE=$(git rev-parse --path-format=absolute --git-dir)/commit-skip

if [ -f $TMP_FILE ]; then
	echo 'Skipping Commitizen step'
	exit 0
fi

exec < /dev/tty && npx czg --hook || true
